### ISSUE TITLE
Any advice on controlling it via a web interface?

### ISSUE THREAD

**Issue by mskogly** [gregpabian/rpi-keyboard-servo-control#1]
The script works perfect, thank you. But would love to be able to control it via a web interface. Any tips on how to integrate that in your code?

**Comment by gregpabian** [comment]
@mskogly please check my other repo, where I'm using WebSockets to control the servos https://github.com/gregpabian/rpi-websockets-servo-control
More details can be found in my blog post https://pixelchinchilla.com/2017/05/diy-video-monitoring-system-part-vi-servo-control-with-websockets/
Good luck!

**Comment by mskogly** [comment]
Wonderful, thanks!
